// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC39fgrZTHL_XNSzwa5qnJFTzaMMPwCAgg',
    appId: '1:929938752072:web:1ccec2e606ee0a2a504e7d',
    messagingSenderId: '929938752072',
    projectId: 'testebanco-88b0c',
    authDomain: 'testebanco-88b0c.firebaseapp.com',
    storageBucket: 'testebanco-88b0c.appspot.com',
    measurementId: 'G-MK8SHD76M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDnEo8R0LsY9p3Ec09kUHddBbr_NSHlsY',
    appId: '1:929938752072:android:7579aae8a82685ee504e7d',
    messagingSenderId: '929938752072',
    projectId: 'testebanco-88b0c',
    storageBucket: 'testebanco-88b0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNZxZaGlqASOK9YNldIfK5J_dQKlzFdME',
    appId: '1:929938752072:ios:f641e0c05cc6b21f504e7d',
    messagingSenderId: '929938752072',
    projectId: 'testebanco-88b0c',
    storageBucket: 'testebanco-88b0c.appspot.com',
    iosClientId: '929938752072-50r2o3b2rsm9mgfgtnscvd3ls38kfrk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.testeBanco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNZxZaGlqASOK9YNldIfK5J_dQKlzFdME',
    appId: '1:929938752072:ios:f641e0c05cc6b21f504e7d',
    messagingSenderId: '929938752072',
    projectId: 'testebanco-88b0c',
    storageBucket: 'testebanco-88b0c.appspot.com',
    iosClientId: '929938752072-50r2o3b2rsm9mgfgtnscvd3ls38kfrk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.testeBanco',
  );
}
